# XScreenSaver Preferences File
# Digital-rain screensaver only, no locking.

timeout:	0:10:00
cycle:		0:10:00
lock:		False
lockTimeout:	0:00:00
passwdTimeout:	0:00:30
dpmsEnabled:	True
dpmsStandby:	2:00:00
dpmsSuspend:	2:00:00
dpmsOff:	4:00:00
grabDesktopImages: False
grabVideoFrames:   False
chooseRandomImages: False
mode:		one
selected:	0
fade:		True
unfade:		False
fadeSeconds:	0:00:02
splash:		False

programs:									      \
			GL: 	glmatrix --root				    \n\
			GL:	cubestorm --root			    \n\
				phosphor -root				    \n
